---
- hosts: all
  tasks:
    - name: install packages
      block:
         - yum:
            name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
         - yum: name={{ item }} state=installed
           with_items:
             - epel-release
             - nginx
             - php70w-fpm
             - php70w-cli
             - php70w-gd
             - php70w-mcrypt
             - php70w-pgsql
             - php70w-pear
             - php70w-xml
             - php70w-mbstring
             - php70w-pdo
             - php70w-json
             - postgresql-server
             - postgresql-contrib
             - python-psycopg2
             - unzip
    - name: prepare
      block:
         - template: src=files/nginx.j2 dest=/etc/nginx/nginx.conf
         - template: src=files/default.j2 dest=/etc/nginx/conf.d/default.conf
         - command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=localhost" -days 3650 -keyout /etc/nginx/owncloud.key -out /etc/nginx/owncloud.crt
         - command: postgresql-setup initdb
         - name: turnoff selinux
           command: setenforce 0
           become: yes
         - get_url: url=https://download.owncloud.org/community/owncloud-10.0.2.zip dest=~/owncloud.zip
         - unarchive:
             src: https://download.owncloud.org/community/owncloud-10.0.2.zip
             remote_src: true
             dest: /
             owner: apache
             group: apache
         - replace:
             path: /var/lib/pgsql/data/pg_hba.conf
             regexp: 'ident$'
             replace: 'trust'
             backup: yes
         - lineinfile:
             path: /etc/selinux/config
             regexp: '^SELINUX='
             line: 'SELINUX=permissive'
         - file:
             path: /var/lib/php/session
             state: directory
             owner: apache
             group: apache
             mode: 0700
    - name: services
      block:
         - service: name=nginx state=started enabled=true
         - service: name=php-fpm state=started enabled=true
         - service: name=postgresql state=started enabled=true
    - name: installation app
      block:
         - uri:
             method: POST
             url: https://127.0.0.1:80/index.php
             validate_certs: no
             body: 'install=true&adminlogin=admin&adminpass=password&adminpass-clone=password&directory=%2Fowncloud%2Fdata&dbtype=pgsql&dbuser=postgres&dbpass=&dbpass-clone=&dbname=postgres&dbhost=localhost'
             follow_redirects: all
             status_code: 401
    # - name: reboot server
    #   block:
    #      - name: Installation is complete. Waiting for running server
    #        shell: nohup bash -c "sleep 2s && reboot" &
    #        async: 0
    #        poll: 0
    #        become: yes
    #        become_method: sudo
    #        ignore_errors: true
