- block:
    - yum:
       name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    - yum: name={{ item }} state=installed
      with_items:
       - epel-release
       - nginx
       - php70w-fpm
       - php70w-cli
       - php70w-gd
       - php70w-mcrypt
       - php70w-pgsql
       - php70w-pear
       - php70w-xml
       - php70w-mbstring
       - php70w-pdo
       - php70w-json
       - python-psycopg2
       - postgresql-server
       - postgresql-contrib
       - unzip
       - python-psycopg2
  rescue:
    - debug:
        msg: Role execution failed
  when:
   - ansible_distribution == "CentOS"
   - ansible_distribution_major_version == "7"

- block:
    - apt: name={{ item }} state=installed
      with_items:
       - nginx
       - php7.0-fpm
       - php7.0-cli
       - php7.0-curl
       - php7.0-zip
       - php7.0-gd
       - php7.0-mcrypt
       - php7.0-pgsql
       - php7.0-xml
       - php7.0-mbstring
       - php7.0-json
       - postgresql
       - postgresql-contrib
       - unzip
       - python-psycopg2
    - name: prepare php-fpm
      lineinfile:
        path: /etc/php/7.0/fpm/pool.d/www.conf
        regexp: '^listen '
        line: 'listen = 127.0.0.1:9000'
  rescue:
    - debug:
        msg: Role execution failed
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "16"
